name: Export Windows Rules

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Collect all Windows rules into /Windows
        run: |
          rm -rf Windows
          mkdir -p Windows

          find synced/Elastic/windows -type f \( -iname "*.yml" -o -iname "*.yaml" \) -exec cp {} Windows/ \;
          find synced/Sigma/windows -type f \( -iname "*.yml" -o -iname "*.yaml" \) -exec cp {} Windows/ \;
          find synced/Yamato/sysmon -type f \( -iname "*.yml" -o -iname "*.yaml" \) -exec cp {} Windows/ \;

          echo "Copied rules:"
          ls -1 Windows | wc -l

      - name: Commit and push Windows folder
        run: |
          git add Windows/
          if git diff --cached --quiet; then
            echo "No changes detected"
            exit 0
          fi
          git commit -m "chore: export Windows rules [automated]"
          git push
