name: Debug Windows Rules Workflow

on:
  workflow_dispatch:  # Manually trigger from GitHub UI

jobs:
  debug-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List rule files
        run: |
          echo "Elastic Rules:"
          find synced/Elastic/windows -name '*.yml' -o -name '*.yaml' || echo "Not found"

          echo "Sigma Rules:"
          find synced/Sigma/windows -name '*.yml' -o -name '*.yaml' || echo "Not found"

          echo "Yamato Rules:"
          find synced/Yamato/sysmon -name '*.yml' -o -name '*.yaml' || echo "Not found"
