name: Process Windows Rules

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch: # Allow manual trigger from GitHub UI

jobs:
  sync-windows-rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Recreate Windows folder and copy rules
        run: |
          rm -rf Windows
          mkdir Windows

          find synced/Elastic/windows -type f \( -iname "*.yml" -o -iname "*.yaml" \) -exec cp {} Windows/ \;
          find synced/Sigma/windows -type f \( -iname "*.yml" -o -iname "*.yaml" \) -exec cp {} Windows/ \;
          find synced/Yamato/sysmon -type f \( -iname "*.yml" -o -iname "*.yaml" \) -exec cp {} Windows/ \;

          echo "Total rules copied:"
          ls -l Windows | wc -l

      - name: Commit and push changes
        run: |
          git add Windows
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update Windows rules folder with latest rules"
            git push
          fi
